---
version: '2.1'
services:
  es-ctl:
    build: ..
    environment:
      WAIT_FOR_SERVICE_UP: tcp://elastic-search:9200
      WAIT_FOR_SERVICE_UP_TIMEOUT: 120s
      ES_ENTRY_POINT: http://elastic:changeme@elastic-search:9200
    depends_on:
      elastic-search:
        condition: service_started

  es-ctl-warning:
    build: ..
    environment:
      WAIT_FOR_SERVICE_UP: tcp://elastic-search:9200
      WAIT_FOR_SERVICE_UP_TIMEOUT: 120s
      ES_ENTRY_POINT: http://elastic:changeme@elastic-search:9200/
    depends_on:
      elastic-search:
        condition: service_started

  elastic-search:
    image: cyberluisda/elasticsearch-kubernetes:5.6.0-xpack
    privileged: true
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx2g"
      NUMBER_OF_MASTERS: "1"
      NETWORK_HOST: 0.0.0.0
      ES_ELASTIC_CONFIG_TRANSPORT_HOST: "transport.host: localhost"
      ES_ELASTIC_DELETE_CONFIG_UNICAST: "ping.unicast.hosts"
    healthcheck:
      test: "nc -z 0.0.0.0 9200 && nc -z localhost 9300"
    ports:
    - 9200:9200
