---
version: '2.1'
services:
  es-ctl:
    build: ..
    environment:
      WAIT_FOR_SERVICE_UP: "tcp://elastic-search:9200"
    depends_on:
      elastic-search:
        condition: service_started

  elastic-search:
    image: cyberluisda/elasticsearch-kubernetes:5.6.0-xpack
    environment:
      NODE_DATA: "true"
      NODE_MASTER: "true"
      NODE_INGEST: "true"
      HTTP_ENABLE: "true"
      ES_JAVA_OPTS: "-Xms256m -Xmx1024g"
    healthcheck:
      test: "nc -z 0.0.0.0 9200"
